# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  android: circleci/android@2.2.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  lint:
    docker:
      - image: cimg/node:19.9.0
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint

  # tests, coverage need added

workflows:
  version: 2.1
  build:
    jobs:
      - lint
